name: Client CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to frontend directory
        run: cd SOLMoi_Frontend

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: SOLMoi_Frontend
        run: npm install

      - name: Build React app
        working-directory: SOLMoi_Frontend
        run: npm run build

      - name: Docker setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        working-directory: SOLMoi_Frontend
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker buildx create --use --name mybuilder || true
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.USERNAME }}/solmoi-client:${{ github.sha }} \
            -t ${{ secrets.USERNAME }}/solmoi-client:latest \
            --push .
