name: Client CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Docker setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker buildx create --use --name mybuilder || true
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.USERNAME }}/solmoi-client:${{ github.sha }} \
            -t ${{ secrets.USERNAME }}/solmoi-client:latest \
            --push .

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH Setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" | sed 's/\r$//' > ~/.ssh/solmoi-key.pem
          chmod 600 ~/.ssh/solmoi-key.pem
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/solmoi-key.pem ubuntu@${{ secrets.AWS_HOST }} "
          export GITHUB_SHA=${{ github.sha }} &&
          cd /home/ubuntu/Client &&
          docker pull ${{ secrets.USERNAME }}/solmoi-client:latest &&
          docker stop solmoi-client || true &&
          docker rm solmoi-client || true &&
          docker run -d --name solmoi-client -p 80:80 ${{ secrets.USERNAME }}/solmoi-client:latest
          "
